name: Deploy to FTP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Namecheap FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: wkeyclub.com
        username: admin@wkeyclub.com
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/
        local-dir: ./
        protocol: ftp
        port: 21
        dangerous-clean-slate: true
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.github/** 